export const STAKING_ABI = [
  "function depositsLive() view returns (bool)",
  "function minDeposit() view returns (uint256)",
  "function dailyRoiBps() view returns (uint256)",
  "function level1MonthlyBps() view returns (uint256)",
  "function level2MonthlyBps() view returns (uint256)",
  "function level3MonthlyBps() view returns (uint256)",
  "function founderMonthlyBps() view returns (uint256)",
  "function level1InstantBps() view returns (uint256)",
  "function founderActivationBps() view returns (uint256)",
  "function earlyWithdrawalPenaltyBps() view returns (uint256)",
  "function totalActivePrincipal() view returns (uint256)",
  "function totalReservedUserRoi() view returns (uint256)",
  "function totalReservedReferralRewards() view returns (uint256)",
  "function totalReservedFounderRewards() view returns (uint256)",
  "function requiredUnreservedUsdt() view returns (uint256)",
  "function availableExcessUsdt() view returns (uint256)",
  "function nextDepositId() view returns (uint256)",
  "function owner() view returns (address)",
  "function referrerOf(address user) view returns (address)",
  "function isFounder(address user) view returns (bool)",
  "function claimableReferralRewards(address user) view returns (uint256)",
  "function claimableFounderRewards(address user) view returns (uint256)",
  "function getUserDepositIds(address user) view returns (uint256[])",
  "function pendingRoi(uint256 depositId) view returns (uint256)",
  "function claimableRoiByDeposit(uint256 depositId) view returns (uint256)",
  "function totalRoiClaimedByDeposit(uint256 depositId) view returns (uint256)",
  "function deposits(uint256 depositId) view returns (uint256 id,address user,uint256 principalUsdt,uint256 tokenEquivalent,uint256 startTime,uint256 endTime,uint256 lastAccrualTime,bool principalWithdrawn,bool closed,address level1,address level2,address level3)",
  "function deposit(uint256 usdtAmount, address referrer)",
  "function claimRoi(uint256 depositId)",
  "function withdrawPrincipal(uint256 depositId)",
  "function claimReferralRewards(uint256[] depositIdsToAccrue)",
  "function claimFounderRewards(uint256[] depositIdsToAccrue)",
  "function accrueDeposits(uint256[] depositIds)"
] as const;
